### ISSUE TITLE
GLOB_BRACE flag is not available on some non GNU systems, like Solaris or Alpine Linux

### ISSUE THREAD

**Issue by stanislavprokopov** [ryssbowh/craft-themes#5] opened 2022-05-14 19:57 UTC
GLOB_BRACE flag is not available on some non GNU systems, like Solaris or Alpine Linux, because of this i am getting following error:

```
Error: Undefined constant "Ryssbowh\CraftThemes\base\GLOB_BRACE" in /app/vendor/ryssbowh/craft-themes/src/base/ThemePlugin.php:367
Stack trace:
#0 /app/vendor/ryssbowh/craft-themes/src/base/ThemePlugin.php(236): Ryssbowh\CraftThemes\base\ThemePlugin->getPreviewImagePath()
#1 /app/vendor/yiisoft/yii2/base/Component.php(139): Ryssbowh\CraftThemes\base\ThemePlugin->getHasPreview()```

**Comment by ryssbowh** [comment] 2022-05-14 20:38
Thanks for reporting, the issue is fixed in 3.1.8 and 4.0.5

**Closed as completed by ryssbowh** 2022-05-14 20:38 UTC
